# Generated by Django 3.2.7 on 2021-10-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('hometown', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('picture', models.ImageField(upload_to='')),
                ('disability', models.BooleanField()),
                ('disability_info', models.CharField(max_length=300)),
                ('transportation', models.BooleanField()),
                ('parent_name', models.CharField(max_length=50)),
                ('parent_address_line', models.CharField(max_length=200)),
                ('parent_occupation', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=10)),
                ('parent_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
